# kickstart travis.
language: java

before_install:
 - git clone https://github.com/ivanceras/parent.git
 - cd parent
 - mvn clean install -Dgpg.skip=true
 - cd ../
 - git clone https://github.com/ivanceras/commons.git
 - cd commons
 - mvn clean install -Dgpg.skip=true
 - cd ../
 - git clone https://github.com/ivanceras/keywordSQL.git
 - cd keywordSQL
 - mvn clean install -Dgpg.skip=true
 - cd ../
 
install: 
 - mvn clean install -Dgpg.skip=true
