# kickstart travis.
language: java

before_install:
 - git clone https://github.com/ivanceras/parent.git
 - cd parent
 - mvn clean install
 - cd ../
 - git clone https://github.com/ivanceras/commons.git
 - cd commons
 - cd ../
 - mvn clean install
 - git clone https://github.com/ivanceras/fluentsql.git
 - cd fluentsql
 - mvn clean install
 - cd ../
