package com.ivanceras.db.server.util.generators;

import static com.ivanceras.db.server.util.DAOGenerator.Array;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import com.ivanceras.commons.conf.Configuration;
import com.ivanceras.commons.strings.CStringUtils;
import com.ivanceras.commons.writer.FileUtil;
import com.ivanceras.commons.writer.SourceWriter;
import com.ivanceras.commons.writer.StringSourceWriter;
import com.ivanceras.db.api.IDatabase;
import com.ivanceras.db.api.ModelDef;
import com.ivanceras.db.shared.datatype.GenericDataType;
import com.ivanceras.db.shared.datatype.JavaDataType;
import com.ivanceras.db.shared.util.SpecialCase;

public class BeanGenerator {


	public boolean start(ModelDef[] modeldef, Configuration conf){
		for(ModelDef model : modeldef){
			generate(model, conf);
		}
		return true;
	}

	
	public boolean generate(ModelDef modeldef, Configuration conf){
		String directory = conf.bodirectory;
		String packageName = conf.bopackageName; 
		
		SourceWriter sw = new StringSourceWriter();
		
		boolean useCamelCase = conf.useCamelCase;
		String className = CStringUtils.capitalize(modeldef.getModelName(), useCamelCase);
		sw.print("package "+packageName+";");
		sw.println("");
		sw.println("/***");
		sw.println("* This is automatically generated by DAOGenerator, based on the database table schema");
		sw.println("* ");
		sw.println("* ");
		sw.println("*/");
		sw.println("import java.io.Serializable;");
		sw.println("");
		sw.println("public class "+className+" implements Serializable{");
		sw.println("/**");
		sw.println(" *"); 
		sw.println(" */");
		sw.println("\tprivate static final long serialVersionUID = "+UUID.randomUUID().getLeastSignificantBits()+"L;");
		sw.println("");

		String[] attributes = modeldef.getAttributes();
		String[] dataTypes = JavaDataType.fromGenericDataType(modeldef.getDataTypes());
		if(modeldef.getSubClass() != null && modeldef.getSubClass().length > 0){
			String[] subclassAttributes = {IDatabase.SUBCLASSTABLE};
			attributes = CStringUtils.mergeString(attributes, subclassAttributes);
			String[] subclassDatatypes = {GenericDataType.STRING};
			dataTypes = CStringUtils.mergeString(dataTypes, subclassDatatypes);
		}
		String[] hasOne = modeldef.getHasOne();
		String[] distinctHasOne = getDistinctString(hasOne);
		String[] hasMany = modeldef.getHasMany();

		for(int i = 0; i < attributes.length; i++){
			String att = SpecialCase.getEquiv(attributes[i]);
			att = CStringUtils.toVariableName(att.toLowerCase(), useCamelCase);
			String datatype = dataTypes[i];
			sw.println("\tprivate "+datatype+" "+att+";");
		}
		for(int i = 0; i < distinctHasOne.length; i++){
			String distinctHasOneStr = CStringUtils.capitalize(distinctHasOne[i].toLowerCase(), useCamelCase);
			String distinctHasOneVar = CStringUtils.toVariableName(distinctHasOneStr, useCamelCase);
			sw.println("");
			sw.println("\tprivate "+distinctHasOneStr+" "+distinctHasOneVar+";");
		}
		for(int i = 0; i < hasMany.length; i++){
			String hasManyStr = CStringUtils.capitalize(hasMany[i].toLowerCase(), useCamelCase);
			String hasManyVar = CStringUtils.toVariableName(hasManyStr, useCamelCase);
			sw.println("");
			sw.println("\tprivate "+hasManyStr+"[] "+hasManyVar+Array+";");
		}


		sw.println("");
		sw.println("");
		sw.println("\tpublic "+className+"(){");
		sw.println("\t\t");
		sw.println("\t}");
		sw.println("");
		for(int i = 0; i < attributes.length; i++){
			String att = SpecialCase.getEquiv(attributes[i]);
			att = CStringUtils.capitalize(att.toLowerCase(), useCamelCase);
			String attVar = CStringUtils.toVariableName(att, useCamelCase); 
			String datatype = dataTypes[i];
			sw.println("\tpublic "+datatype+" get"+att+"(){");
			sw.println("\t\treturn "+attVar+";");
			sw.println("\t}");
			sw.println("");
			sw.println("\tpublic void set"+att+"("+datatype+" "+attVar+"){");
			sw.println("\t\tthis."+attVar+" = "+attVar+";");
			sw.println("\t}");
			sw.println("");
		}

		for(int i = 0; i < distinctHasOne.length; i++){
			String distinctHasOneStr = CStringUtils.capitalize(distinctHasOne[i].toLowerCase(), useCamelCase);
			String distinctHasOneVar = CStringUtils.toVariableName(distinctHasOneStr, useCamelCase);
			sw.println("");
			sw.println("\tpublic void set"+distinctHasOneStr+"("+distinctHasOneStr+" "+distinctHasOneVar+"){");
			sw.println("\t\tthis."+distinctHasOneVar+" = "+distinctHasOneVar+";");
			sw.println("\t}");
			sw.println("");
			sw.println("\tpublic "+distinctHasOneStr+" get"+distinctHasOneStr+"(){");
			sw.println("\t\treturn "+distinctHasOneVar+";");
			sw.println("\t}");
		}


		for(int i = 0; i < hasMany.length; i++){
			String hasManyStr = CStringUtils.capitalize(hasMany[i].toLowerCase(), useCamelCase);
			String hasManyVar = CStringUtils.toVariableName(hasManyStr, useCamelCase);
			sw.println("");
			sw.println("\tpublic void set"+hasManyStr+Array+"("+hasManyStr+"[] "+hasManyVar+Array+"){");
			sw.println("\t\tthis."+hasManyVar+Array+" = "+hasManyVar+Array+";");
			sw.println("\t}");
			sw.println("");
			sw.println("\tpublic "+hasManyStr+"[] get"+hasManyStr+Array+"(){");
			sw.println("\t\treturn "+hasManyVar+Array+";");
			sw.println("\t}");
		}

		sw.println("}");
		FileUtil.writeToFile(sw.toString(), directory, ""+className+".java");
		return true;
	}

	public static String[] getDistinctString(String[] hasOne) {
		List<String> distinctString = new ArrayList<String>();
		for(String h : hasOne){
			if(distinctString.contains(h)){
				;
			}else{
				distinctString.add(h);
			}
		}
		return distinctString.toArray(new String[distinctString.size()]);
	}
}
