package com.ivanceras.db.server.util.generators;

import com.ivanceras.commons.conf.Configuration;
import static com.ivanceras.db.server.util.DAOGenerator.Array;
import com.ivanceras.commons.strings.CStringUtils;
import com.ivanceras.commons.writer.FileUtil;
import com.ivanceras.commons.writer.SourceWriter;
import com.ivanceras.commons.writer.StringSourceWriter;
import com.ivanceras.db.api.DAO_Operator;
import com.ivanceras.db.api.EntityManager;
import com.ivanceras.db.api.IDatabase;
import com.ivanceras.db.api.ModelDef;
import com.ivanceras.db.shared.DAO;
import com.ivanceras.db.shared.datatype.GenericDataType;
import com.ivanceras.db.shared.datatype.JavaDataType;
import com.ivanceras.db.shared.util.SpecialCase;

public class DAOClassGenerator {
	
	
	private boolean generateDAOClass(ModelDef modeldef, Configuration conf, boolean useCentralizeString, boolean includeDepracated){
		SourceWriter sw = new StringSourceWriter();
		String directory = conf.daodirectory;
		String packageName = conf.daopackageName;
		String modelName = modeldef.getModelName();
		boolean useCamelCase = conf.useCamelCase;
		if(useCamelCase){
			modelName = CStringUtils.camelCaseUnderscores(modelName);
		}
		String className = CStringUtils.capitalize(modelName, useCamelCase);
		String varClassName = CStringUtils.toVariableName(className, useCamelCase);
		sw.print("package "+packageName+";");
		sw.println("");
		sw.println("/***");
		sw.println("* This is automatically generated by DAOGenerator, based on the database table schema");
		sw.println("* ");
		sw.println("* ");
		sw.println("*/");
		sw.println("");
		sw.println("import "+DAO.class.getCanonicalName()+";");
		sw.println("import "+DAO_Operator.class.getCanonicalName()+";");
		sw.println("import "+conf.metaDataPackageName+".Column;");
		sw.println("public class DAO_"+className+" extends DAO{");
		sw.println("/**");
		sw.println(" *"); 
		sw.println(" */");

		String[] attributes = modeldef.getAttributes();
		String[] dataTypes = JavaDataType.fromGenericDataType(modeldef.getDataTypes());
		if(modeldef.getSubClass() != null && modeldef.getSubClass().length > 0){
			String[] subclassAttributes = {IDatabase.SUBCLASSTABLE};
			attributes = CStringUtils.mergeString(attributes, subclassAttributes);
			String[] subclassDatatypes = {GenericDataType.STRING};
			dataTypes = CStringUtils.mergeString(dataTypes, subclassDatatypes);
		}
		String[] hasOne = modeldef.getHasOne();
		String[] distinctHasOne = BeanGenerator.getDistinctString(hasOne);
		String[] hasMany = modeldef.getHasMany();


		sw.println("");
		sw.println("");
		sw.println("\tpublic DAO_"+className+"(){");
		sw.println("\t\tsuper(\""+className+"\");");
		sw.println("\t}");
		sw.println("");
		for(int i = 0; i < attributes.length; i++){
			//			System.out.println("attribute["+i+"]: "+attributes[i]);
			String att = SpecialCase.getEquiv(attributes[i]);
			String columnName = CStringUtils.toVariableName(att);
			att = CStringUtils.capitalize(att.toLowerCase(),useCamelCase);
			String attVar = CStringUtils.toVariableName(att,useCamelCase);
			String datatype = dataTypes[i];
			sw.println("\tpublic "+datatype+" get"+att+"(){");
			sw.println("\t\treturn ("+datatype+")get_Value(Column."+columnName+");");
			sw.println("\t}");
			sw.println("");
			sw.println("\tpublic void set"+att+"("+datatype+" "+attVar+"){");
			sw.println("\t\tset_Value(Column."+columnName+", "+attVar+");");
			sw.println("\t}");
			sw.println("");
		}

		for(int i = 0; i < distinctHasOne.length; i++){
			String distinctHasOneStr = CStringUtils.capitalize(distinctHasOne[i].toLowerCase(),useCamelCase);
			String distinctHasOneVar = CStringUtils.toVariableName(distinctHasOneStr,useCamelCase);
			sw.println("");
			sw.println("\tpublic void set"+distinctHasOneStr+"(DAO_"+distinctHasOneStr+" "+distinctHasOneVar+"){");
			sw.println("\t\tset_Value(\""+distinctHasOne[i]+"\", "+distinctHasOneVar+");");
			sw.println("\t}");
			sw.println("");
			sw.println("\tpublic DAO_"+distinctHasOneStr+" get"+distinctHasOneStr+"(){");
			sw.println("\t\treturn (DAO_"+distinctHasOneStr+")get_Value(\""+distinctHasOne[i]+"\");");
			sw.println("\t}");
		}


		for(int i = 0; i < hasMany.length; i++){
			String hasManyStr = CStringUtils.capitalize(hasMany[i].toLowerCase(),useCamelCase);
			String hasManyVar = CStringUtils.toVariableName(hasManyStr,useCamelCase);
			sw.println("");
			sw.println("\tpublic void set"+hasManyStr+Array+"(DAO_"+hasManyStr+"[] "+hasManyVar+Array+"){");
			sw.println("\t\tset_Value(\""+hasMany[i]+Array+"\", "+hasManyVar+Array+");");
			sw.println("\t}");
			sw.println("");
			sw.println("\tpublic DAO_"+hasManyStr+"[] get"+hasManyStr+Array+"(){");
			sw.println("\t\treturn (DAO_"+hasManyStr+"[])get_Value(\""+hasMany[i]+Array+"\");");
			sw.println("\t}");
		}
		if(includeDepracated){
			sw.println("");
			sw.println("\t/**");
			sw.println("\t * @deprecated user{@link "+EntityManager.class.getSimpleName()+".cast(DAO_"+className+".class, dao); instead))}");
			sw.println("\t * @param dao");
			sw.println("\t * @return DAO_"+className+"");
			sw.println("\t */");
			sw.println("\t@Deprecated");
			sw.println("\tpublic static DAO_"+className+" cast(DAO dao){");
			sw.println("\t\tif(dao == null){");
			sw.println("\t\t\treturn null;");
			sw.println("\t\t}");
			sw.println("\t\telse if(DAO_"+className+".class.equals(dao.getClass())){");
			sw.println("\t\t\treturn (DAO_"+className+") dao;");
			sw.println("\t\t}");
			sw.println("\t\telse{");
			sw.println("\t\t\tDAO_"+className+" "+varClassName+" = "+DAO_Operator.class.getSimpleName()+".cast(new DAO_"+className+"(), \""+className+"\", dao);");
			sw.println("\t\t\treturn "+varClassName+";");
			sw.println("\t\t}");
			sw.println("\t}");
			sw.println("\t");
			sw.println("\t/**");
			sw.println("\t * @deprecated user{@link "+EntityManager.class.getSimpleName()+".cast(DAO_"+className+".class, daoArray); instead))}");
			sw.println("\t * @param daoArray");
			sw.println("\t * @return DAO_"+className+"[]");
			sw.println("\t */");
			sw.println("\t@Deprecated");
			sw.println("\tpublic static DAO_"+className+"[] cast(DAO[] daoArray){");
			sw.println("\t\tif(daoArray == null){");
			sw.println("\t\t\treturn null;");
			sw.println("\t\t}");
			sw.println("\t\telse if(DAO_"+className+"[].class.equals(daoArray.getClass())){");
			sw.println("\t\t\treturn (DAO_"+className+"[]) daoArray;");
			sw.println("\t\t}");
			sw.println("\t\telse{");
			sw.println("\t\t\tDAO_"+className+"[] "+varClassName+Array+" = "+DAO_Operator.class.getSimpleName()+".cast(new DAO_"+className+"[daoArray.length],\""+className+"\", daoArray);");
			sw.println("\t\t\treturn "+varClassName+Array+";");
			sw.println("\t\t}");
			sw.println("\t}");
		}

		sw.println("\t");

		sw.println("}");
		FileUtil.writeToFile(sw.toString(), directory, "DAO_"+className+".java");
		return true;
	}

	public void start(ModelDef[] modelList, Configuration conf, boolean useCentralizeString,
			boolean includeDepracated) {
		for(ModelDef model : modelList){
			generateDAOClass(model, conf, useCentralizeString, includeDepracated);
		}
		
	}
}
