package com.ivanceras.db.server.util.generators;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.ivanceras.db.api.ModelDef;
import com.ivanceras.commons.conf.Configuration;
import com.ivanceras.commons.writer.FileUtil;
import com.ivanceras.commons.writer.SourceWriter;
import com.ivanceras.commons.writer.StringSourceWriter;
public class TableNameGenerator {

	public void start(ModelDef[] modelList, Configuration conf){
		Set<String> columnSet = new HashSet<String>();
		Map<String, Set<String>> usedInTable = new HashMap<String, Set<String>>();
		Set<String> uniquetableSet = new HashSet<String>();

		for(int i = 0; i < modelList.length; i++){
			ModelDef modeldef = modelList[i];
			uniquetableSet.add(modeldef.getTableName());
			List<String> attrList = Arrays.asList(modeldef.getAttributes());
			for(String att : attrList){
				columnSet.add(att);
				if(usedInTable.containsKey(att)){
					usedInTable.get(att).add(modeldef.getModelName());
				}
				else{
					HashSet<String> tableSet = new HashSet<String>();
					tableSet.add(modeldef.getModelName());
					usedInTable.put(att, tableSet);
				}
			}
		}
		createTableNameList(uniquetableSet, conf.metaDataPackageName,  conf.metaDataDirectory, "Table");
	}

	private void createTableNameList(Set<String> uniquetableSet,
			String metaDataPackageName, String metaDataDirectory, String className) {

		List<String> orderedList = new ArrayList<String>();
		for(String table : uniquetableSet){
			orderedList.add(table);
		}

		SourceWriter sw = new StringSourceWriter();
		sw.lnprint("package "+metaDataPackageName+";");
		sw.lnprint();
		sw.lnprint("/***");
		sw.lnprint("* This is automatically generated by DAOGenerator, based on the database table schema");
		sw.lnprint("* ");
		sw.lnprint("* ");
		sw.lnprint("*/");
		sw.lnprint();
		sw.lnprint("public class "+className+"{");
		for(String table : orderedList){
			sw.lnprint("\tpublic final static String "+table+" = \""+table+"\";");
		}
		sw.lnprint("");
		sw.lnprint("}");
		FileUtil.writeToFile(sw.toString(), metaDataDirectory, className+".java");	
	}

}
