package com.ivanceras.db.sample;

/***
* This is automatically generated by DAOGenerator, based on the database table schema
* 
* 
*/

public class Column{

	/**Used in table [Order_line, Orders, Category, Invoice, Organization, Address, Product, Photo, Product_availability, User_info, Users, Base, Cart_line, Wishlist_line, Product_category, Record, Wishlist, Client, Settings, Cart]*/
	public final static String updatedby = "updatedby";

	/**Used in table [Photo]*/
	public final static String data = "data";

	/**Used in table [Organization]*/
	public final static String parent_organization_id = "parent_organization_id";

	/**Used in table [Product_availability]*/
	public final static String available = "available";

	/**Used in table [Order_line]*/
	public final static String discount = "discount";

	/**Used in table [Product_availability]*/
	public final static String open_time = "open_time";

	/**Used in table [Cart_line]*/
	public final static String cart_line_id = "cart_line_id";

	/**Used in table [Orders]*/
	public final static String date_approved = "date_approved";

	/**Used in table [Orders]*/
	public final static String total_items = "total_items";

	/**Used in table [Order_line, Orders, Category, Invoice, Organization, Address, Product, Photo, Product_availability, User_info, Users, Base, Cart_line, Wishlist_line, Product_category, Record, Wishlist, Client, Settings, Cart]*/
	public final static String client_id = "client_id";

	/**Used in table [Product_availability]*/
	public final static String available_day = "available_day";

	/**Used in table [Product]*/
	public final static String is_service = "is_service";

	/**Used in table [Cart_line, Cart]*/
	public final static String cart_id = "cart_id";

	/**Used in table [Users]*/
	public final static String password = "password";

	/**Used in table [Order_line, Orders, Category, Invoice, Organization, Address, Product, Photo, Product_availability, User_info, Users, Base, Cart_line, Wishlist_line, Product_category, Record, Wishlist, Client, Settings, Cart]*/
	public final static String createdby = "createdby";

	/**Used in table [Product]*/
	public final static String price = "price";

	/**Used in table [Order_line, Cart_line, Wishlist_line, Product, Product_availability, Product_category]*/
	public final static String product_id = "product_id";

	/**Used in table [Invoice]*/
	public final static String invoice_id = "invoice_id";

	/**Used in table [Order_line]*/
	public final static String order_line_id = "order_line_id";

	/**Used in table [Order_line]*/
	public final static String freight_amt = "freight_amt";

	/**Used in table [Address]*/
	public final static String longitude = "longitude";

	/**Used in table [Product]*/
	public final static String info = "info";

	/**Used in table [Product_availability]*/
	public final static String available_until = "available_until";

	/**Used in table [User_info]*/
	public final static String current_location = "current_location";

	/**Used in table [Product, Photo]*/
	public final static String seq_no = "seq_no";

	/**Used in table [Order_line, Orders, Category, Invoice, Organization, Address, Product, Photo, Product_availability, User_info, Users, Base, Cart_line, Wishlist_line, Product_category, Record, Wishlist, Client, Settings, Cart]*/
	public final static String created = "created";

	/**Used in table [Organization, Address, User_info]*/
	public final static String address_id = "address_id";

	/**Used in table [Order_line, Orders, Category, Invoice, Organization, Address, Product, Photo, User_info, Users, Cart_line, Wishlist_line, Record, Wishlist, Client, Settings, Cart]*/
	public final static String active = "active";

	/**Used in table [Orders]*/
	public final static String grand_total_amount = "grand_total_amount";

	/**Used in table [Wishlist_line, Wishlist]*/
	public final static String wishlist_id = "wishlist_id";

	/**Used in table [Product_availability]*/
	public final static String close_time = "close_time";

	/**Used in table [Orders]*/
	public final static String date_ordered = "date_ordered";

	/**Used in table [Product]*/
	public final static String tags = "tags";

	/**Used in table [Product]*/
	public final static String unit = "unit";

	/**Used in table [Settings]*/
	public final static String use_metric = "use_metric";

	/**Used in table [User_info, Users, Settings]*/
	public final static String user_id = "user_id";

	/**Used in table [Order_line, Orders, Category, Invoice, Organization, Address, Product, Photo, Product_availability, User_info, Users, Base, Cart_line, Wishlist_line, Product_category, Record, Wishlist, Client, Settings, Cart]*/
	public final static String organization_id = "organization_id";

	/**Used in table [Cart_line]*/
	public final static String qty = "qty";

	/**Used in table [Order_line, Orders, Category, Invoice, Organization, Address, Product, Photo, User_info, Users, Cart_line, Wishlist_line, Record, Wishlist, Client, Settings, Cart]*/
	public final static String name = "name";

	/**Used in table [Orders]*/
	public final static String date_invoiced = "date_invoiced";

	/**Used in table [Orders]*/
	public final static String processing = "processing";

	/**Used in table [Order_line, Orders, Category, Invoice, Organization, Address, Product, Photo, Product_availability, User_info, Users, Base, Cart_line, Wishlist_line, Product_category, Record, Wishlist, Client, Settings, Cart]*/
	public final static String updated = "updated";

	/**Used in table [Order_line, Orders, Invoice]*/
	public final static String order_id = "order_id";

	/**Used in table [Orders]*/
	public final static String amount_tendered = "amount_tendered";

	/**Used in table [Photo]*/
	public final static String photo_id = "photo_id";

	/**Used in table [Address]*/
	public final static String latitude = "latitude";

	/**Used in table [Order_line, Orders, Category, Invoice, Organization, Address, Product, Photo, User_info, Users, Cart_line, Wishlist_line, Record, Wishlist, Client, Settings, Cart]*/
	public final static String description = "description";

	/**Used in table [Order_line]*/
	public final static String qty_ordered = "qty_ordered";

	/**Used in table [Product, Product_availability]*/
	public final static String stocks = "stocks";

	/**Used in table [Orders]*/
	public final static String amount_refunded = "amount_refunded";

	/**Used in table [Wishlist_line]*/
	public final static String wishlist_line_id = "wishlist_line_id";

	/**Used in table [Product]*/
	public final static String parent_product_id = "parent_product_id";

	/**Used in table [Product]*/
	public final static String use_parent_price = "use_parent_price";

	/**Used in table [Product_availability]*/
	public final static String always_available = "always_available";

	/**Used in table [Category, Product_category]*/
	public final static String category_id = "category_id";

	/**Used in table [Product]*/
	public final static String currency = "currency";

	/**Used in table [Invoice]*/
	public final static String is_paid = "is_paid";

	/**Used in table [Orders]*/
	public final static String charges_amount = "charges_amount";

	/**Used in table [Orders]*/
	public final static String is_tax_included = "is_tax_included";

	/**Used in table [Settings]*/
	public final static String value = "value";

	/**Used in table [Users]*/
	public final static String email = "email";

	/**Used in table [Orders]*/
	public final static String is_confirmed = "is_confirmed";

	/**Used in table [Order_line, Wishlist_line]*/
	public final static String price_momentary = "price_momentary";

	/**Used in table [Product_availability]*/
	public final static String available_from = "available_from";

	/**Used in table [Orders]*/
	public final static String is_invoiced = "is_invoiced";

	/**Used in table [Photo]*/
	public final static String url = "url";

	/**Used in table [Wishlist_line]*/
	public final static String added_to_cart = "added_to_cart";

	/**Used in table [Order_line, Orders, Category, Invoice, Organization, Address, Product, Photo, User_info, Users, Cart_line, Wishlist_line, Record, Wishlist, Client, Settings, Cart]*/
	public final static String help = "help";

	/**Used in table [Orders]*/
	public final static String processed = "processed";

	/**Used in table [Settings]*/
	public final static String settings_id = "settings_id";

	/**Used in table [User_info]*/
	public final static String displayname = "displayname";

	/**Used in table [Orders]*/
	public final static String is_approved = "is_approved";

	/**Used in table [Orders]*/
	public final static String customer_name = "customer_name";
	public final static String subclasstable = "subclasstable";

	/**Used in table [Product]*/
	public final static String upfront_fee = "upfront_fee";

	/**Used in table [Users]*/
	public final static String username = "username";

}
