package com.ivanceras.db.sample;
/***
* This is automatically generated by DAOGenerator, based on the database table schema
* 
* 
*/

import com.ivanceras.db.shared.DAO;
import com.ivanceras.db.api.DAO_Operator;
public class DAO_ProductCategory extends DAO{
/**
 *
 */


	public DAO_ProductCategory(){
		super("ProductCategory");
	}

	public java.util.UUID getOrganizationId(){
		return (java.util.UUID)get_Value(Column.organization_id);
	}

	public void setOrganizationId(java.util.UUID organizationId){
		set_Value(Column.organization_id, organizationId);
	}

	public java.util.UUID getClientId(){
		return (java.util.UUID)get_Value(Column.client_id);
	}

	public void setClientId(java.util.UUID clientId){
		set_Value(Column.client_id, clientId);
	}

	public java.util.Date getCreated(){
		return (java.util.Date)get_Value(Column.created);
	}

	public void setCreated(java.util.Date created){
		set_Value(Column.created, created);
	}

	public java.util.UUID getCreatedby(){
		return (java.util.UUID)get_Value(Column.createdby);
	}

	public void setCreatedby(java.util.UUID createdby){
		set_Value(Column.createdby, createdby);
	}

	public java.util.Date getUpdated(){
		return (java.util.Date)get_Value(Column.updated);
	}

	public void setUpdated(java.util.Date updated){
		set_Value(Column.updated, updated);
	}

	public java.util.UUID getUpdatedby(){
		return (java.util.UUID)get_Value(Column.updatedby);
	}

	public void setUpdatedby(java.util.UUID updatedby){
		set_Value(Column.updatedby, updatedby);
	}

	public java.util.UUID getProductId(){
		return (java.util.UUID)get_Value(Column.product_id);
	}

	public void setProductId(java.util.UUID productId){
		set_Value(Column.product_id, productId);
	}

	public java.util.UUID getCategoryId(){
		return (java.util.UUID)get_Value(Column.category_id);
	}

	public void setCategoryId(java.util.UUID categoryId){
		set_Value(Column.category_id, categoryId);
	}


	public void setCategory(DAO_Category category){
		set_Value("category", category);
	}

	public DAO_Category getCategory(){
		return (DAO_Category)get_Value("category");
	}

	public void setProduct(DAO_Product product){
		set_Value("product", product);
	}

	public DAO_Product getProduct(){
		return (DAO_Product)get_Value("product");
	}

	public void setProductCategory(DAO_ProductCategory productCategory){
		set_Value("product_category", productCategory);
	}

	public DAO_ProductCategory getProductCategory(){
		return (DAO_ProductCategory)get_Value("product_category");
	}

	public void setProductCategoryList(DAO_ProductCategory[] productCategoryList){
		set_Value("product_categoryList", productCategoryList);
	}

	public DAO_ProductCategory[] getProductCategoryList(){
		return (DAO_ProductCategory[])get_Value("product_categoryList");
	}
	
}
