package com.ivanceras.db.sample;

/***
* This is automatically generated by com.ivanceras.db.server.util.generators.DAOClassGenerator, based on the database table schema
* 
* 
*/

import com.ivanceras.db.shared.DAO;
public class DAO_Users extends DAO{
/**
 *
 */


	public DAO_Users(){
		super("Users");
	}

	public java.util.UUID getOrganizationId(){
		return (java.util.UUID)get_Value(Column.organization_id);
	}

	public void setOrganizationId(java.util.UUID organizationId){
		set_Value(Column.organization_id, organizationId);
	}

	public java.util.UUID getClientId(){
		return (java.util.UUID)get_Value(Column.client_id);
	}

	public void setClientId(java.util.UUID clientId){
		set_Value(Column.client_id, clientId);
	}

	public java.util.Date getCreated(){
		return (java.util.Date)get_Value(Column.created);
	}

	public void setCreated(java.util.Date created){
		set_Value(Column.created, created);
	}

	public java.util.UUID getCreatedby(){
		return (java.util.UUID)get_Value(Column.createdby);
	}

	public void setCreatedby(java.util.UUID createdby){
		set_Value(Column.createdby, createdby);
	}

	public java.util.Date getUpdated(){
		return (java.util.Date)get_Value(Column.updated);
	}

	public void setUpdated(java.util.Date updated){
		set_Value(Column.updated, updated);
	}

	public java.util.UUID getUpdatedby(){
		return (java.util.UUID)get_Value(Column.updatedby);
	}

	public void setUpdatedby(java.util.UUID updatedby){
		set_Value(Column.updatedby, updatedby);
	}

	public String getName(){
		return (String)get_Value(Column.name);
	}

	public void setName(String name){
		set_Value(Column.name, name);
	}

	public String getDescription(){
		return (String)get_Value(Column.description);
	}

	public void setDescription(String description){
		set_Value(Column.description, description);
	}

	public String getHelp(){
		return (String)get_Value(Column.help);
	}

	public void setHelp(String help){
		set_Value(Column.help, help);
	}

	public Boolean getActive(){
		return (Boolean)get_Value(Column.active);
	}

	public void setActive(Boolean active){
		set_Value(Column.active, active);
	}

	public java.util.UUID getUserId(){
		return (java.util.UUID)get_Value(Column.user_id);
	}

	public void setUserId(java.util.UUID userId){
		set_Value(Column.user_id, userId);
	}

	public String getUsername(){
		return (String)get_Value(Column.username);
	}

	public void setUsername(String username){
		set_Value(Column.username, username);
	}

	public String getPassword(){
		return (String)get_Value(Column.password);
	}

	public void setPassword(String password){
		set_Value(Column.password, password);
	}

	public String getEmail(){
		return (String)get_Value(Column.email);
	}

	public void setEmail(String email){
		set_Value(Column.email, email);
	}


}