package com.ivanceras.db.sample;
/***
* This is automatically generated by DAOGenerator, based on the database table schema
* 
* 
*/

import com.ivanceras.db.shared.DAO;
import com.ivanceras.db.api.DAO_Operator;
public class DAO_Product extends DAO{
/**
 *
 */


	public DAO_Product(){
		super("Product");
	}

	public java.util.UUID getOrganizationId(){
		return (java.util.UUID)get_Value(Column.organization_id);
	}

	public void setOrganizationId(java.util.UUID organizationId){
		set_Value(Column.organization_id, organizationId);
	}

	public java.util.UUID getClientId(){
		return (java.util.UUID)get_Value(Column.client_id);
	}

	public void setClientId(java.util.UUID clientId){
		set_Value(Column.client_id, clientId);
	}

	public java.util.Date getCreated(){
		return (java.util.Date)get_Value(Column.created);
	}

	public void setCreated(java.util.Date created){
		set_Value(Column.created, created);
	}

	public java.util.UUID getCreatedby(){
		return (java.util.UUID)get_Value(Column.createdby);
	}

	public void setCreatedby(java.util.UUID createdby){
		set_Value(Column.createdby, createdby);
	}

	public java.util.Date getUpdated(){
		return (java.util.Date)get_Value(Column.updated);
	}

	public void setUpdated(java.util.Date updated){
		set_Value(Column.updated, updated);
	}

	public java.util.UUID getUpdatedby(){
		return (java.util.UUID)get_Value(Column.updatedby);
	}

	public void setUpdatedby(java.util.UUID updatedby){
		set_Value(Column.updatedby, updatedby);
	}

	public String getName(){
		return (String)get_Value(Column.name);
	}

	public void setName(String name){
		set_Value(Column.name, name);
	}

	public String getDescription(){
		return (String)get_Value(Column.description);
	}

	public void setDescription(String description){
		set_Value(Column.description, description);
	}

	public String getHelp(){
		return (String)get_Value(Column.help);
	}

	public void setHelp(String help){
		set_Value(Column.help, help);
	}

	public Boolean getActive(){
		return (Boolean)get_Value(Column.active);
	}

	public void setActive(Boolean active){
		set_Value(Column.active, active);
	}

	public java.util.UUID getProductId(){
		return (java.util.UUID)get_Value(Column.product_id);
	}

	public void setProductId(java.util.UUID productId){
		set_Value(Column.product_id, productId);
	}

	public java.util.UUID getParentProductId(){
		return (java.util.UUID)get_Value(Column.parent_product_id);
	}

	public void setParentProductId(java.util.UUID parentProductId){
		set_Value(Column.parent_product_id, parentProductId);
	}

	public Boolean getIsService(){
		return (Boolean)get_Value(Column.is_service);
	}

	public void setIsService(Boolean isService){
		set_Value(Column.is_service, isService);
	}

	public java.math.BigDecimal getPrice(){
		return (java.math.BigDecimal)get_Value(Column.price);
	}

	public void setPrice(java.math.BigDecimal price){
		set_Value(Column.price, price);
	}

	public Boolean getUseParentPrice(){
		return (Boolean)get_Value(Column.use_parent_price);
	}

	public void setUseParentPrice(Boolean useParentPrice){
		set_Value(Column.use_parent_price, useParentPrice);
	}

	public String getUnit(){
		return (String)get_Value(Column.unit);
	}

	public void setUnit(String unit){
		set_Value(Column.unit, unit);
	}

	public java.math.BigDecimal getStocks(){
		return (java.math.BigDecimal)get_Value(Column.stocks);
	}

	public void setStocks(java.math.BigDecimal stocks){
		set_Value(Column.stocks, stocks);
	}

	public String getTags(){
		return (String)get_Value(Column.tags);
	}

	public void setTags(String tags){
		set_Value(Column.tags, tags);
	}

	public String getInfo(){
		return (String)get_Value(Column.info);
	}

	public void setInfo(String info){
		set_Value(Column.info, info);
	}

	public String getCurrency(){
		return (String)get_Value(Column.currency);
	}

	public void setCurrency(String currency){
		set_Value(Column.currency, currency);
	}

	public Integer getSeqNo(){
		return (Integer)get_Value(Column.seq_no);
	}

	public void setSeqNo(Integer seqNo){
		set_Value(Column.seq_no, seqNo);
	}

	public java.math.BigDecimal getUpfrontFee(){
		return (java.math.BigDecimal)get_Value(Column.upfront_fee);
	}

	public void setUpfrontFee(java.math.BigDecimal upfrontFee){
		set_Value(Column.upfront_fee, upfrontFee);
	}


	public void setProductAvailability(DAO_ProductAvailability productAvailability){
		set_Value("product_availability", productAvailability);
	}

	public DAO_ProductAvailability getProductAvailability(){
		return (DAO_ProductAvailability)get_Value("product_availability");
	}

	public void setCategoryList(DAO_Category[] categoryList){
		set_Value("categoryList", categoryList);
	}

	public DAO_Category[] getCategoryList(){
		return (DAO_Category[])get_Value("categoryList");
	}
	
}
