package com.ivanceras.db.sample;

/***
* This is automatically generated by DAOGenerator, based on the database table schema
* 
* 
*/

public class Table{
	public final static String settings = "settings";
	public final static String product = "product";
	public final static String address = "address";
	public final static String wishlist = "wishlist";
	public final static String photo = "photo";
	public final static String cart = "cart";
	public final static String users = "users";
	public final static String wishlist_line = "wishlist_line";
	public final static String user_info = "user_info";
	public final static String order_line = "order_line";
	public final static String organization = "organization";
	public final static String product_availability = "product_availability";
	public final static String record = "record";
	public final static String client = "client";
	public final static String orders = "orders";
	public final static String invoice = "invoice";
	public final static String category = "category";
	public final static String cart_line = "cart_line";
	public final static String product_category = "product_category";
	public final static String base = "base";

}
